name: ci
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: generateGhPage
        run: |
          git clone https://github.com/Willie169/Willie169.git
          cd Willie169
          node generateGhPage.js
          mv output.html ..
          cd ..
          rm -rf Willie169
      - name: Commit GitHub page
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          mv output.html index.html
          git add index.html
          if git diff --cached --quiet; then
            echo "No GitHub page changes"
          else
            git commit -m "Update GitHub page"
            git push
          fi
